---
- name: Import key generation tasks
  import_tasks: __create/gen_key.yml

- name: Create WireGuard configuration with peers
  ansible.builtin.template:
    src: "{{ wireguard_interface }}.conf.j2"
    dest: "/etc/wireguard/{{ wireguard_interface }}.conf"
    owner: root
    group: root
    mode: '0600'
  become: true