---
- name: Installing Helix
  ansible.builtin.package:
    name: helix
    state: present

- name: Create hx symlink for Archlinux
  ansible.builtin.file:
    src: /usr/bin/helix
    dest: /usr/bin/hx
    state: link
  when: ansible_distribution == 'Archlinux'

- name: Installing Language Servers
  ansible.builtin.package:
    name: "{{ _helix_language_server }}"
    state: present
  loop_control:
    loop_var: _helix_language_server
  loop: "{{ helix_language_server }}"
