---
# Variables:
#    git (dic)
#    git.configuration (list): List of configuration settings for different folders
#    git.repositories (list): List of repositories to clone
git_user: "{{ system_users[0].name }}"
git_base:
  dir: "/home/{{ git_user }}/git"
  owner: "{{ git_user }}"
  group: "{{ git_user }}"
