---
- name: Setup archlinux installation
  hosts: localhost
  become: true
  roles:
    - common
    #- sshd
    - podman
    - pacman
    #- editor
    #- git
    - udev
    - firewalld
    #- wireguard
    #- obs-studio
    - vim
    - nix
    - direnv
    - cups
    - gnome-keyring
    #- headroom
    - ollama
    - opencode
    #- whisrs
    #- thinkpad_dock
    # - openvpn
