---
- name: Setup archlinux installation
  hosts: localhost
  become: true
  roles:
    - common
    - podman
    - pacman
    - editor
    - git
    - conky
    - obs-studio
    - nix
    - cups
    - thinkpad_dock
    # - openvpn
