---
lazyvim_config_path: /home/{{ lazyvim_user }}/.config/nvim

lazyvim_dependencies:
  - neovim
  - git
  - otf-monaspace-nerdfonts
  - tree-sitter-cli
  - curl
  - fzf
  - ripgrep
  - fd
  - ghostty
