---
# handlers file for gnome-keyring
- name: Restart polkit agent
  ansible.builtin.systemd:
    name: polkit-gnome-authentication-agent-1.service
    scope: user
    state: restarted
    daemon_reload: true
  become: true
  become_user: "{{ gnome_keyring_user }}"
