---
# tasks file for system_user

- name: Create the declared accounts
  ansible.builtin.include_tasks: add.yml
  loop_control:
    loop_var: system_user_account
    label: "{{ system_user_account.name }}"
  loop: "{{ system_user_accounts }}"
