---
# defaults file for editor
editor_default: vim


# https://langserver.org/
# Supported by helix: https://docs.helix-editor.com/lang-support.html
editor_helix_language_server:
  - gopls # for Go, gomod, gotmpl, gowork
  - python-lsp-server # python
  # - dockerfile-language-server # dockerfiles currently only in AUR!
  - yaml-language-server # yaml
  - texlab # latex
  - lua-language-server # lua
  # - haskell-language-server # haskell
  - bash-language-server # bash
  - vscode-json-languageserver # json
  - vscode-html-languageserver # html
  - vscode-css-languageserver # css
