---
# tasks file for podman
- name: Gather the package facts
  ansible.builtin.package_facts:
    manager: auto

- name: Installing podman Package
  ansible.builtin.package:
    name: podman
    state: present

- name: Replace Docker
  ansible.builtin.import_tasks: replace_docker.yml
  when: podman_replace_docker

- name: Installing cockpit extension for podman
  ansible.builtin.package:
    name: cockpit-podman
    state: present
  when: "'cockpit' in ansible_facts.packages"

- name: Setup rootless podman
  ansible.builtin.import_tasks: rootless.yml
  when: podman_rootless