---
- name: Installing rootless dependencies
  ansible.builtin.package:
    name: "{{ _podman_rootless_dependencies }}"
    state: present
  loop_control:
    loop_var: _podman_rootless_dependencies
  loop:
    - fuse-overlayfs
    - slirp4netns

- name: Enable kernel.unprivileged_userns_clone
  ansible.posix.sysctl:
    name: kernel.unprivileged_userns_clone
    value: '1'
    state: present
    sysctl_set: true

- name: Creating subuid und subgid files
  ansible.builtin.copy:
    content: ""
    dest: "{{ _podman_rootless_files }}"
    force: false
    group: root
    owner: root
    mode: '0644'
  loop_control:
    loop_var: _podman_rootless_files
  loop:
    - /etc/subuid
    - /etc/subgid

- name: Adding subuids and subgid for privileged users
  ansible.builtin.lineinfile:
    path: >-
      {{ lookup('vars'), ansible_loop_var[1] }}
    line: >-
      {{ lookup('vars'), ansible_loop_var[0] }}:100000:65535
    regexp: '^{{_podman_rootless_user }}:\d*:\d*$'
  register: podman_set_privileged
  loop_control:
    loop_var: _podman_rootless
  loop: >-
    {{ _podman_rootless_user | product( _podman_rootless_file ) }}
  vars:
    _podman_rootless_user: >-
      {{ podman_rootless_users }}
    _podman_rootless_file:
      - /etc/subuid
      - /etc/subgid

- name: Propagate changes to subuid and subgid
  ansible.builtin.command:
    cmd: 'podman system migrate'
  when: podman_set_privileged.changed
