---
# tasks file for pacman

- name: Configure pacman.conf
  ansible.builtin.include_tasks: __configure/conf.yml

- name: Set up the weekly cache cleanup
  ansible.builtin.include_tasks: __configure/paccache.yml
  when: pacman_paccache
