---
- name: Install dependencies
  ansible.builtin.package:
    name: "{{ lazyvim_dependencies }}"
    state: present
  become: true

- name: Create Backup with current neovim setup
  ansible.builtin.copy:
    remote_src: True
    src: "{{ lazyvim_config_path }}"
    dest: "{{ lazyvim_config_path }}.back"
  when: lazyvim_save_install

- name: Remove old configuration
  ansible.builtin.file:
    path: "{{ lazyvim_config_path }}"
    state: absent

- name: Clone lazyvim starter
  ansible.builtin.git:
    repo: https://github.com/LazyVim/starter
    dest: "{{ lazyvim_config_path }}"
    
- name: Set permissions to lazyvim user
  ansible.builtin.file:
    path: "{{ lazyvim_config_path }}"
    owner: "{{ lazyvim_user }}"
    group: "{{ lazyvim_user }}"
    mode: '0755'
    state: directory
    recurse: True

- name: Remove .git folder from configuration
  ansible.builtin.file:
    path: "{{ lazyvim_config_path }}/.git"
    state: absent
