---
- name: Install nix package manager
  ansible.builtin.package:
    name: nix
    state: present

- name: Start and enable nix deamon
  ansible.builtin.systemd:
    name: nix-daemon
    state: started
    enabled: true

- name: Add users to the nix-users Group
  ansible.builtin.user:
    name: "{{ _nix_user }}"
    groups: nix-users
    append: true
  loop_control:
    loop_var: _nix_user
  loop: "{{ nix_users }}"

- name: Setup Max Jobs to auto
  ansible.builtin.lineinfile:
    path: /etc/nix/nix.conf
    regexp: "^max-jobs(.*)?=(.*)?"
    line: max-jobs = auto