---
# tasks file for udev

- name: Install the rules declared for this host
  ansible.builtin.include_tasks: add_rule.yml
  loop_control:
    loop_var: udev_rule
    label: "{{ udev_rule.name }}"
  loop: "{{ udev_rules }}"
