---
# vars file for common
common_packages_default:
  # Editors
  - helix
  - neovim
  # - visual-studio-code-bin Aktuell nur AUR!
  # Terminal helper
  - eza
  - yazi
  - htop
  - btop
  - tree
  - tmux
  - unzip
  - mosh
  - lsd
  - fzf
  - bat
  - duf
  - git-delta
  - jujutsu
  - lazyjj
  - fd
  - zoxide
  - mcfly
  - ripgrep
  - direnv
  ## - cheat # Aktuell nur AUR!
  # Backup/Restore
  - chezmoi
  - restic
  ## - ventoy # Aktuell nur AUR!
  - vorta
  - seahorse
  - rsync
  # Networking
  - nmap
  - tcpdump
  # Virtualisation
  - virt-viewer
  # Office
  - evolution
  - xournalpp
  - nextcloud-client
  - libreoffice-fresh
  #- libreoffice-fresh-de
