---
# vars file for common
common_packages_default:
  # Editors
  - helix
  - neovim
  # - visual-studio-code-bin Aktuell nur AUR!
  # Terminal helper
  - eza
  - yazi
  - htop
  - tree
  - tmux
  - unzip
  - mosh
  - lsd
  - fzf
  - bat
  - duf
  - fd
  - zoxide
  - mcfly
  - ripgrep
  ## - cheat # Aktuell nur AUR!
  # Backup/Restore
  - chezmoi
  - restic
  ## - ventoy # Aktuell nur AUR!
  - vorta
  - rsync
  # Networking
  - nmap
  - tcpdump
  # Virtualisation
  - virt-viewer
